// Every construct the BotGuard interpreter actually uses, evaluated to a
// string. Run under node and under js2py and diff: a difference here is a
// difference the VM can trip over.
var CASES = [
  ['bit >>> on negative', function () { return (-1 >>> 0) + ',' + (-5 >>> 2); }],
  ['bit | 0 on big', function () { return (4294967296 | 0) + ',' + (2147483648 | 0) + ',' + (1e20 | 0); }],
  ['bit << 31', function () { return (1 << 31) + ',' + (1 << 32) + ',' + (3 << 30); }],
  ['bit ^ and ~', function () { return (12345 ^ 67890) + ',' + (~7) + ',' + (~-1); }],
  ['shift by >32', function () { return (1 << 33) + ',' + (16 >> 33) + ',' + (-16 >>> 33); }],
  ['number toString 36', function () { return (123456789).toString(36) + ',' + (0.5).toString(2); }],
  ['number toString rounding', function () { return String(0.1 + 0.2) + ',' + String(1e21) + ',' + String(1e-7); }],
  ['parseInt radix', function () { return parseInt('0x1f') + ',' + parseInt('08') + ',' + parseInt('z', 36) + ',' + parseInt('  12ab'); }],
  ['String.fromCharCode', function () { return String.fromCharCode(65, 0x1F600 & 0xFFFF, 0xD83D, 0xDE00).length + ',' + String.fromCharCode(300).charCodeAt(0); }],
  ['charCodeAt out of range', function () { return String('ab'.charCodeAt(5)) + ',' + 'ab'.charCodeAt(0); }],
  ['string slice negatives', function () { return 'abcdef'.slice(-2) + ',' + 'abcdef'.substring(4, 2) + ',' + 'abcdef'.substr(-3, 2); }],
  ['split with regex', function () { return JSON.stringify('a1b22c'.split(/\d+/)) + ',' + JSON.stringify('a,b,,c'.split(',')); }],
  ['split with limit', function () { return JSON.stringify('a b c d'.split(' ', 2)); }],
  ['replace with $1', function () { return 'John Smith'.replace(/(\w+)\s(\w+)/, '$2 $1'); }],
  ['replace with function', function () { return 'a1b2'.replace(/\d/g, function (m) { return '[' + m + ']'; }); }],
  ['replace $& and $$', function () { return 'abc'.replace('b', '$$$&$&'); }],
  ['regex exec loop', function () { var r = /\d/g, s = 'a1b2c3', o = [], m; while ((m = r.exec(s))) o.push(m.index + ':' + m[0]); return o.join(','); }],
  ['regex lastIndex', function () { var r = /a/g; r.test('aa'); return r.lastIndex + ',' + r.test('aa') + ',' + r.lastIndex; }],
  ['regex match all', function () { return JSON.stringify('a1b22'.match(/\d+/g)); }],
  ['regex no match', function () { return String('abc'.match(/\d/)) + ',' + JSON.stringify('abc'.match(/\d/g)); }],
  ['regex groups undefined', function () { var m = /(a)(b)?/.exec('a'); return m.length + ',' + String(m[2]); }],
  ['sort default is string', function () { return [10, 9, 1, 100].sort().join(','); }],
  ['sort comparator', function () { return [3, 1, 2].sort(function (a, b) { return a - b; }).join(','); }],
  ['sort stability', function () { var a = [[1,'a'],[0,'b'],[1,'c'],[0,'d']]; a.sort(function(x,y){return x[0]-y[0];}); return a.map(function(p){return p[1];}).join(''); }],
  ['array holes', function () { var a = [1, , 3]; return a.length + ',' + String(a[1]) + ',' + a.join('-'); }],
  ['splice', function () { var a = [1,2,3,4]; var r = a.splice(1, 2, 'x'); return a.join(',') + '|' + r.join(','); }],
  ['concat and slice', function () { return [1,2].concat([3],[4,[5]]).length + ',' + [1,2,3].slice(-2).join(''); }],
  ['array to string', function () { return String([1,[2,3],null,undefined]) + ',' + String([]); }],
  ['object key order', function () { var o = {}; o.b = 1; o[2] = 1; o.a = 1; o[1] = 1; var k = []; for (var x in o) k.push(x); return k.join(','); }],
  ['Object.keys order', function () { var o = {b: 1, 2: 1, a: 1, 1: 1}; return Object.keys(o).join(','); }],
  ['delete and in', function () { var o = {a: 1}; delete o.a; return ('a' in o) + ',' + ('toString' in o); }],
  ['hasOwnProperty', function () { return {a:1}.hasOwnProperty('a') + ',' + {}.hasOwnProperty('toString'); }],
  ['prototype chain', function () { function A(){}; A.prototype.x = 1; function B(){}; B.prototype = new A(); var b = new B(); return b.x + ',' + (b instanceof A); }],
  ['__proto__ assign', function () { var o = {}; o.__proto__ = {y: 7}; return String(o.y); }],
  ['arguments object', function () { return (function () { arguments[0] = 9; return arguments.length + ',' + arguments[0]; })(1, 2, 3); }],
  ['arguments to array', function () { return (function () { return Array.prototype.slice.call(arguments).join(''); })(1, 2, 3); }],
  ['apply array-like', function () { return Math.max.apply(null, [1, 5, 3]) + ',' + (function(a,b){return a+b;}).apply(null, {0:1,1:2,length:2}); }],
  ['this in call', function () { function f() { return typeof this; } return f() + ',' + f.call(null) + ',' + f.call(5); }],
  ['closure in loop', function () { var f = []; for (var i = 0; i < 3; i++) f.push(function () { return i; }); return f[0]() + '' + f[1]() + f[2](); }],
  ['try finally return', function () { return (function () { try { return 'a'; } finally { } })() + (function () { try { throw 1; } catch (e) { return 'b'; } finally { } })(); }],
  ['catch scoping', function () { var e = 'outer'; try { throw 'inner'; } catch (e) { } return e; }],
  ['throw non-error', function () { try { throw [1, 2]; } catch (e) { return typeof e + ',' + e.length; } }],
  ['labelled block', function () { var r = 'x'; a: { r = 'in'; break a; } return r; }],
  ['labelled continue', function () { var s = ''; outer: for (var i = 0; i < 3; i++) { for (var j = 0; j < 3; j++) { if (j) continue outer; s += '' + i + j; } } return s; }],
  ['switch fallthrough', function () { var s = ''; switch (2) { case 1: s += '1'; case 2: s += '2'; case 3: s += '3'; break; case 4: s += '4'; } return s; }],
  ['switch on expression', function () { var s = 'no'; switch (true) { case [] == true: s = 'arr'; break; case '' == 0: s = 'empty'; break; } return s; }],
  ['comma operator', function () { var a; return (a = 1, a += 2, a) + ',' + (0, 'x'); }],
  ['void and typeof', function () { return String(void 0) + ',' + typeof undeclaredThing + ',' + typeof null; }],
  ['loose equality', function () { return ([] == false) + ',' + ([0] == false) + ',' + (null == undefined) + ',' + (NaN == NaN) + ',' + ('' == 0); }],
  ['plus coercion', function () { return ([] + {}) + ',' + (1 + '2') + ',' + ('3' * '4') + ',' + (true + true); }],
  ['increment on string', function () { var s = '5'; s++; return s + ',' + typeof s; }],
  ['Date arithmetic', function () { var d = new Date(1700000000000); return d.getTime() + ',' + (+d) + ',' + (typeof (new Date() - 0)); }],
  ['JSON round trip', function () { return JSON.stringify(JSON.parse('{"b":1,"a":[1,null,true]}')); }],
  ['JSON undefined', function () { return String(JSON.stringify({a: undefined, b: function () {}, c: 1})); }],
  ['encodeURIComponent', function () { return encodeURIComponent('a b/c?d=é') + ',' + escape('a b'); }],
  ['Math', function () { return Math.floor(-1.5) + ',' + Math.round(-1.5) + ',' + Math.round(2.5) + ',' + Math.pow(2, 31) + ',' + Math.abs(-0); }],
  ['string comparison', function () { return ('a' < 'b') + ',' + ('Z' < 'a') + ',' + ('10' < '9'); }],
  ['defineProperty getter', function () { var o = {}; Object.defineProperty(o, 'x', {get: function () { return 42; }}); return String(o.x); }],
  ['defineProperty enumerable', function () { var o = {}; Object.defineProperty(o, 'h', {value: 1, enumerable: false}); var k = []; for (var p in o) k.push(p); return k.length + ',' + o.h; }],
  ['Object.create', function () { var o = Object.create({z: 3}); return String(o.z) + ',' + Object.keys(o).length; }],
  ['getOwnPropertyNames', function () { return Object.getOwnPropertyNames({a: 1, b: 2}).sort().join(','); }],
  ['function length and name', function () { function f(a, b, c) {} return f.length + ',' + f.name; }],
  ['bind', function () { function f(a) { return this.x + a; } return String(f.bind({x: 1})(2)); }],
  ['new with return object', function () { function F() { return {y: 1}; } return String(new F().y); }],
  ['instanceof through bind', function () { function F() {} return (new F()) instanceof F; }],
  ['string to number edge', function () { return Number('') + ',' + Number(' 12 ') + ',' + Number('0x10') + ',' + Number('1e3') + ',' + String(Number('abc')); }],
  ['array length assign', function () { var a = [1,2,3]; a.length = 1; return a.join(',') + ',' + a.length; }],
  ['sparse forEach', function () { var n = 0; [1, , 3].forEach(function () { n++; }); return String(n); }],
  ['string repeat via join', function () { return new Array(4).join('ab'); }],
  ['toString of array of fn', function () { return typeof [function(){}].join(','); }],
  ['Number toFixed', function () { return (1.005).toFixed(2) + ',' + (1e21).toFixed(2); }],
  ['Date.now type', function () { return typeof Date.now() + ',' + (Date.now() > 1e12); }],
  ['Date valueOf', function () { var d = new Date(); return typeof (d + 0) + ',' + typeof (+d) + ',' + typeof d.getTime(); }],
  ['performance-like sum', function () { var o = {t: Date.now()}; return typeof (o.t + 5); }],
  ['isNaN and isFinite', function () { return isNaN('x') + ',' + isFinite('10') + ',' + isNaN(undefined); }]
];
function __run() {
  var out = [], i, name, v;
  for (i = 0; i < CASES.length; i++) {
    name = CASES[i][0];
    try { v = String(CASES[i][1]()); } catch (e) { v = 'THREW ' + (e && e.message || e); }
    out.push(name + ' => ' + v);
  }
  return out;
}
