// Second batch: what the trace shows the VM leaning on -- array surgery,
// string slicing, bit arithmetic, scope and eval -- plus the corners a
// translator is most likely to get wrong.
var CASES2 = [
  ['shift/pop/unshift', function () { var a = [1,2,3]; return a.shift() + ',' + a.pop() + ',' + (a.unshift(9), a.join('-')); }],
  ['push returns length', function () { var a = []; return a.push(1) + ',' + a.push(2, 3); }],
  ['join on nested', function () { return [1,[2,[3]],4].join('-'); }],
  ['join with null', function () { return [null, undefined, 0, ''].join('|'); }],
  ['splice negative', function () { var a = [1,2,3,4,5]; return a.splice(-2, 1).join('') + '|' + a.join(''); }],
  ['splice no deleteCount', function () { var a = [1,2,3,4]; return a.splice(2).join('') + '|' + a.join(''); }],
  ['slice on arguments', function () { return (function () { return [].slice.call(arguments, 1).join(''); })(1,2,3); }],
  ['concat spreads arrays only', function () { return [1].concat(2, [3], [[4]]).length; }],
  ['indexOf with fromIndex', function () { return [1,2,1].indexOf(1, 1) + ',' + [1,2].indexOf(3); }],
  ['array length beyond', function () { var a = []; a[5] = 1; return a.length + ',' + a.join('-'); }],
  ['reverse in place', function () { var a = [1,2,3]; a.reverse(); return a.join(''); }],
  ['sort undefined last', function () { return [3, undefined, 1].sort().join(','); }],
  ['string charCodeAt loop', function () { var s = 'abc', o = []; for (var i = 0; i < s.length; i++) o.push(s.charCodeAt(i)); return o.join('.'); }],
  ['fromCharCode.apply', function () { return String.fromCharCode.apply(null, [104, 105]); }],
  ['string indexOf empty', function () { return 'abc'.indexOf('') + ',' + 'abc'.indexOf('', 10); }],
  ['string slice past end', function () { return 'abc'.slice(1, 99) + ',' + 'abc'.slice(5) + '|'; }],
  ['replace all with regex g', function () { return 'aaa'.replace(/a/g, 'b'); }],
  ['replace only first', function () { return 'aaa'.replace('a', 'b'); }],
  ['replace with newline', function () { return 'a\nb'.replace(/\n/g, '~'); }],
  ['split empty string', function () { return JSON.stringify('abc'.split('')) + ',' + JSON.stringify(''.split(',')); }],
  ['trim', function () { return '[' + '  a  '.trim() + ']'; }],
  ['string + number', function () { return ('5' - 2) + ',' + ('5' + 2) + ',' + (+'0b11'); }],
  ['unary minus on string', function () { return (-'3') + ',' + String(-'a'); }],
  ['modulo negatives', function () { return (-7 % 3) + ',' + (7 % -3) + ',' + (5.5 % 2); }],
  ['division by zero', function () { return (1/0) + ',' + (-1/0) + ',' + String(0/0); }],
  ['exponent-ish', function () { return Math.pow(2, 53) + ',' + (Math.pow(2, 53) + 1); }],
  ['integer overflow in +', function () { return (9007199254740993 + 0) + ',' + (0.1 * 3); }],
  ['bit ops chain', function () { var x = 0; for (var i = 0; i < 8; i++) x = (x << 5) - x + i; return x + ',' + (x >>> 0); }],
  ['xor rolling hash', function () { var h = 5381, s = 'botguard'; for (var i = 0; i < s.length; i++) h = ((h << 5) + h) ^ s.charCodeAt(i); return h + ',' + (h >>> 0); }],
  ['Uint8Array basics', function () { var a = new Uint8Array(4); a[0] = 300; a[1] = -1; return a[0] + ',' + a[1] + ',' + a.length; }],
  ['Uint8Array from array', function () { var a = new Uint8Array([1, 2, 300]); return a[2] + ',' + a.length; }],
  ['Uint8Array join', function () { var a = new Uint8Array([1,2,3]); return Array.prototype.join.call(a, '-'); }],
  ['Int32Array wrap', function () { var a = new Int32Array(1); a[0] = 2147483648; return String(a[0]); }],
  ['typed array typeof', function () { var a = new Uint8Array(1); return typeof a + ',' + (a instanceof Uint8Array) + ',' + Object.prototype.toString.call(a); }],
  ['function hoisting', function () { var r = typeof inner; function inner() {} return r; }],
  ['var hoisting', function () { var r = typeof later; var later = 1; return r; }],
  ['named function expression', function () { var f = function me(n) { return n ? me(n - 1) + '.' : 'x'; }; return f(3); }],
  ['recursion depth 200', function () { function f(n) { return n ? f(n - 1) + 1 : 0; } return String(f(200)); }],
  ['arguments aliasing', function () { return (function (a) { a = 5; return arguments[0]; })(1); }],
  ['arguments.callee', function () { return (function () { return typeof arguments.callee; })(); }],
  ['closure counter', function () { function mk() { var n = 0; return function () { return ++n; }; } var c = mk(); c(); return String(c()); }],
  ['this in nested function', function () { var o = {v: 1, m: function () { var self = this; return (function () { return self.v; })(); }}; return String(o.m()); }],
  ['call with primitive this', function () { return (function () { return typeof this; }).call('s'); }],
  ['bind partial', function () { function f(a, b) { return a + b; } return String(f.bind(null, 1)(2)); }],
  ['new on bound', function () { function F(a) { this.a = a; } var B = F.bind(null, 7); return String(new B().a); }],
  ['getter on prototype', function () { function A() {} Object.defineProperty(A.prototype, 'g', {get: function () { return 5; }}); return String(new A().g); }],
  ['setter', function () { var seen; var o = {}; Object.defineProperty(o, 's', {set: function (v) { seen = v; }}); o.s = 3; return String(seen); }],
  ['writable false', function () { var o = {}; Object.defineProperty(o, 'w', {value: 1, writable: false}); o.w = 2; return String(o.w); }],
  ['freeze', function () { var o = Object.freeze({a: 1}); o.a = 2; o.b = 3; return o.a + ',' + String(o.b) + ',' + Object.isFrozen(o); }],
  ['seal and extensible', function () { var o = Object.seal({a: 1}); o.b = 1; return String(o.b) + ',' + Object.isExtensible(o); }],
  ['getOwnPropertyDescriptor', function () { var d = Object.getOwnPropertyDescriptor({a: 1}, 'a'); return d.value + ',' + d.writable + ',' + d.enumerable; }],
  ['for-in over chain', function () { function A() {} A.prototype.p = 1; var o = new A(); o.own = 2; var k = []; for (var x in o) k.push(x); return k.join(','); }],
  ['delete from array', function () { var a = [1,2,3]; delete a[1]; return a.length + ',' + String(a[1]) + ',' + a.join('-'); }],
  ['in on array', function () { var a = [1]; a[3] = 1; return (1 in a) + ',' + (2 in a); }],
  ['try finally overrides', function () { return (function () { try { return 'a'; } finally { return 'b'; } })(); }],
  ['nested throw rethrow', function () { try { try { throw 'x'; } finally { } } catch (e) { return e; } }],
  ['throw inside catch', function () { try { try { throw 1; } catch (e) { throw 2; } } catch (e) { return String(e); } }],
  ['eval sees local', function () { var q = 7; return String(eval('q * 6')); }],
  ['eval declares in caller', function () { eval('var made = 3;'); return String(typeof made === "undefined" ? "gone" : made); }],
  ['eval returns last value', function () { return String(eval('1; 2; 3')); }],
  ['eval of function expression', function () { return typeof eval('(function(){})'); }],
  ['indirect eval is global', function () { var g = (0, eval); return typeof g('this'); }],
  ['new Function scope', function () { var outside = 1; try { return String(new Function('return typeof outside')()); } catch (e) { return 'threw'; } }],
  ['switch on strings', function () { switch ('b') { case 'a': return 'A'; case 'b': return 'B'; default: return 'D'; } }],
  ['do while', function () { var n = 0; do { n++; } while (n < 3); return String(n); }],
  ['for with multiple', function () { var s = ''; for (var i = 0, j = 3; i < j; i++, j--) s += '' + i + j; return s; }],
  ['ternary chain', function () { var x = 2; return x === 1 ? 'a' : x === 2 ? 'b' : 'c'; }],
  ['logical returns operand', function () { return String(0 || 'x') + ',' + String('' && 'y') + ',' + String(null || undefined); }],
  ['string object vs primitive', function () { return (typeof new String('a')) + ',' + (new String('a') == 'a') + ',' + (new String('a') === 'a'); }],
  ['Number object', function () { return (typeof new Number(1)) + ',' + (new Number(1) + 1); }],
  ['array of objects sort by key', function () { var a = [{k:2},{k:1}]; a.sort(function (x, y) { return x.k - y.k; }); return a[0].k + ',' + a[1].k; }],
  ['JSON nested order', function () { return JSON.stringify({z: 1, a: {y: 2, b: 3}, 0: 4}); }],
  ['JSON with toJSON', function () { return JSON.stringify({toJSON: function () { return 'T'; }}); }],
  ['JSON.parse reviver', function () { return JSON.stringify(JSON.parse('{"a":1}', function (k, v) { return typeof v === 'number' ? v * 2 : v; })); }],
  ['regexp source and flags', function () { var r = /ab+/gi; return r.source + ',' + r.global + ',' + r.ignoreCase; }],
  ['regexp special chars', function () { return 'a.b'.replace(/\./, '-') + ',' + 'a|b'.split(/\|/).join('+'); }],
  ['regexp backreference', function () { return /(\w)\1/.test('aa') + ',' + /(\w)\1/.test('ab'); }],
  ['regexp non greedy', function () { return String('<a><b>'.match(/<.+?>/)[0]); }],
  ['regexp anchors multiline', function () { return String('a\nb'.match(/^b$/m)); }],
  ['encode/decodeURI', function () { return decodeURIComponent(encodeURIComponent('a+b c')) + ',' + encodeURI('a b'); }],
  ['String.raw-ish escapes', function () { return '\x41B\101'.length + ',' + '\x41B'; }],
  ['toString on object', function () { return String({}) + ',' + String({toString: function () { return 'T'; }}); }],
  ['valueOf preferred in +', function () { var o = {valueOf: function () { return 2; }, toString: function () { return 'S'; }}; return (o + 1) + ',' + String(o); }]
];
function __run2() {
  var out = [], i, name, v;
  for (i = 0; i < CASES2.length; i++) {
    name = CASES2[i][0];
    try { v = String(CASES2[i][1]()); } catch (e) { v = 'THREW ' + (e && e.message || e); }
    out.push(name + ' => ' + v);
  }
  return out;
}
